version: '3.8'
services:
  app:
    build:
      context: '.'
      dockerfile: Dockerfile
    volumes:
      - ../:/workspaces/blog-goapp:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/blog_goapp_dev
      TEST_DATABASE_URL: ecto://postgres:postgres@db/blog_goapp_test
    command: sleep infinity
    networks:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: blog_goapp_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  backend: {}

volumes:
  postgres-data: {}
